name: BuilderAuditSys
version: '${project.version}'
main: com.mcsls.builderauditsys.BuilderAuditSys
api-version: 1.19
load-before:
  - WorldGuard

commands:
  sba:
    description: 开始建筑类玩家审核

  sbp:
    description: 设置建筑类玩家审核的计算原点

  pass:
    description: 管理员设置当前的建筑通过审核